# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628325cead2f707fb4ccfeafbca511664743506be6bc56688a292c6d59e585cf4aa4aab22088fb54f086e9818869c11d619b877b40ab1d4a4bcbf2802d473235

test:
  secret_key_base: d024d1795f4cacd7db0c221a4d4bc2a3c2637c9e5f10ac3a7828f23c5696db8352e3af321a968ba2f7433e31fde04ed481d862ecae5b459c9e0009e68d62e3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
